### ISSUE TITLE
Comparing data from multiple sources

### ISSUE THREAD

**Issue by kgowda** [openmhealth/shimmer#58] opened 2016-06-27 15:07 UTC
Hi,

My problem statement is to incentivize users based on their fitness data collected from a wide variety of sources. 

The real problem: "Each of these sources have a varying level of accuracy. The same user has reported different step count on multiple apps. Likewise 2 users walking the same number of steps have different multiple readings on different sources"

How do we deal with this situation? Appreciate your help.

Thanks.

**Comment by Groulien** [comment] 2016-06-27 18:03
Disclaimer: I am not affiliated with the developers of Shimmer.

The difference in accuracy is caused by different devices using different methods of measurement.
The difference in accuracy per person can be caused by a great deal of environmental factors.

How you deal with this difference would depend on your business case but there are three possibilities (for steps).
1. Take the average
2. Keep the highest or lowest
3. Prefer one Shim/Source over another.

Ask your product owner or customer which of these is most valuable.
If user retention and positive feedback are important, keeping the highest value might be a good idea.

**Comment by emersonf** [comment] 2016-06-28 08:16
4. Normalize, weight, or score the data based on its source.
5. Calculate rewards based on changes per app, not across apps.

As @Groulien said, it really depends on the devices you're trying to achieve. 

We use the [omh-developers](https://groups.google.com/forum/#!forum/omh-developers) Google group for higher-level discussions like this, so I'm closing this issue and suggest you move the conversation there if you want a wider audience.

**Closed by emersonf** 2016-06-28 08:16 UTC

**Comment by kgowda** [comment] 2016-06-28 08:57
Sure. Will move the conversation there! Thanks @Groulien @emersonf
